name: "Build migrate_gse script (Windows)"

on:
  workflow_call:
    # needed since it allows this to become a reusable workflow
  workflow_dispatch:
    # allows manual trigger

permissions:
  contents: "write"

env:
  ARTIFACT_NAME: "migrate_gse-win-${{ github.sha }}"
  SCRIPT_BASE_DIR: "tools/migrate_gse"
  PACKAGE_BASE_DIR: "tools/migrate_gse/bin/win"

  THIRD_PARTY_BASE_DIR: "third-party"

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    defaults:
      run:
        shell: powershell

    steps:
      - name: "Configure git line endings"
        run: |
          git config --system core.autocrlf false
          git config --global core.autocrlf false

      - name: "Checkout branch"
        uses: actions/checkout@v4

      # extra helpers/tools, these are not built inside the deps build dir
      - name: "Clone third-party deps (build/win)"
        uses: actions/checkout@v4
        with:
          ref: "third-party/build/win"
          path: "${{env.THIRD_PARTY_BASE_DIR}}/build/win"

      - name: "Install env"
        working-directory: "${{ env.SCRIPT_BASE_DIR }}"
        run: cmd /c recreate_venv_win.bat

      - name: "Rebuild"
        working-directory: "${{ env.SCRIPT_BASE_DIR }}"
        run: cmd /c rebuild_win.bat

      # upload artifact
      - name: "Upload build package"
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: "${{ env.PACKAGE_BASE_DIR }}/"
          if-no-files-found: "error"
          compression-level: 9
          retention-days: 1
